name: test1_dart
version: 0.0.3
authors:
- oss alibaba <alibabaopensource@gmail.com>
description: >
  a test dart package.
homepage: https://github.com/peze/dart-test

environment:
  sdk: '>=2.0.0 <3.0.0'
